apiVersion: v1
kind: Template
parameters:
- name: "APP_NAME"
  displayName: "Application name"
  description: "Name of your application"
  value: wildfly-kitchensink-app

objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  spec:
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: DockerImage
          name: docker.io/openshift/wildfly-100-centos7
    source:
      type: Binary
    output:
      to:
        kind: ImageStreamTag
name: wildfly-kitchensink-app:latest