#!/usr/bin/groovy

def k8s_token = '<unknown>'

node ('master') {
    k8s_token = readFile '/var/run/secrets/kubernetes.io/serviceaccount/token'
}

node('maven') {

    def k8s_namespace = readFile '/var/run/secrets/kubernetes.io/serviceaccount/namespace'

    stage 'Checkout'
    checkout scm

    stage 'Build'
    sh 'cd kitchensink && mvn clean compile'

    stage 'Package'
    sh 'cd kitchensink && mvn package'

    stage 'Archive artifact'
    sh 'mkdir -p artifacts/deployments && cp kitchensink/target/*.war artifacts/deployments'
    archive 'kitchensink/target/*.war'

    stage 'Create Image'
    sh "oc login https://kubernetes.default/ --token=${k8s_token} --certificate-authority=/run/secrets/kubernetes.io/serviceaccount/ca.crt"

    // Prepare the deployments so you can see pipeline in console overview when running for the first time
    sh 'oc process -f kitchensink/.openshift-pipeline/empty-deployment-template.yaml -v "APP_NAME=wildfly-kitchensink-app" | oc apply -f -'

    sh 'oc process -f https://github.com/tnozicka/openshift-templates/raw/master/binary-build-template.yaml \
       -v "APP_NAME=wildfly-kitchensink-app,BUILDER_IMAGE=docker.io/openshift/wildfly-100-centos7,OUTPUT_IMAGESTREAM_TAG=wildfly-kitchensink-app:latest" | oc create -f -'
    sh 'oc start-build wildfly-kitchensink-app --from-dir=artifacts/ --follow'

    stage 'Deploy'
    sh "oc process -f kitchensink/.openshift-pipeline/deployment-template.yaml -v 'APP_NAME=wildfly-kitchensink-app,IMAGE_STREAM_NAMESPACE=${k8s_namespace},IMAGE_STREAM_TAG=wildfly-kitchensink-app:latest' | oc apply -f -"
    sh 'oc annotate is wildfly-kitchensink-app misc_$(date +%s)=foo || true' // Hack for 0-2 minute pause caused by https://github.com/openshift/origin/issues/9018
    sh 'sleep 50'
    sh "PODNAME=\$(oc get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{end}}' --selector='deploymentConfig=wildfly-kitchensink-app') && oc exec $PODNAME bash /wildfly/bin/add-user.sh adminUser adminPassword ManagementRealm"

    stage 'Run Integration Tests'
    sh "cp kitchensink/.openshift-pipeline/arquillian.xml kitchensink/src/test/resources/arquillian.xml"
    sh "cd kitchensink && HOSTNAME=\$(oc get routes -o go-template --template '{{range .items}}{{.spec.host}}{{end}}' --selector='application=wildfly-kitchensink-app') && MANAGEMENT_ADDRESS=\$(oc get routes -o go-template --template '{{range .items}}{{.spec.host}}{{end}}' --selector='application=management-service') && mvn test -Parq-wildfly-remote"

}