apiVersion: v1
kind: Template
metadata:
  annotations:
    desrciption: "Template for generating BuildConfigs with jenkinsPipelineStrategy."
    tags: ""
parameters:
- name: "GIT_URL"
  displayName: "Git URL"
  description: "URL to git source repository containing Jenkinsfile. (e.g. https://github.com/tnozicka/jboss-eap-quickstarts.git)"
  required: true
- name: "GIT_REF"
  displayName: "Git Reference"
  description: "Git reference. (branch, ...)"
  value: "master"
- name: "GITHUB_WEBHOOK_SECRET"
  displayName: "GitHub Webhook secret"
  value: "kontinu8"
objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: wildfly-kitchensink-app-pipeline
    labels:
      app: wildfly-kitchensink-app
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "wildfly-kitchensink-app", "namespace": "", "kind": "DeploymentConfig"}]'
  spec:
    triggers:
#      - type: ConfigChange
      - type: GitHub
        github:
          secret: "${GITHUB_WEBHOOK_SECRET}"
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: kitchensink/.openshift-pipeline/Jenkinsfile
    source:
      type: git
      git:
        uri: ${GIT_URL}
        ref: ${GIT_REF}
